### ISSUE TITLE
💡 [需求] <增加状态栏图标“流量节省程序”隐藏开关>

### ISSUE THREAD

**Issue by QingXuer** [Team-Cemiuiler/Cemiuiler#194]
### 需求内容

如题， 增驾状态栏图标“流量节省程序”隐藏开关
![IMG_20230626_202210](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/97309254/7785ec92-11b3-4ee4-8e31-b3d5083bda20)

### 简单例子

为系统界面-状态栏-图标内增加“流量节省程序”隐藏开关
![IMG_20230626_202210](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/97309254/7c4a14b3-450e-4d86-a1ac-89b17038d621)

**Comment by HChenX** [comment]
已经实现
