### ISSUE TITLE
🐛 [BUG] <手机管家：应用状态控制无效>

### ISSUE THREAD

**Issue by Mrqqeat** [Team-Cemiuiler/Cemiuiler#211]
### 问题描述

功能：手机管家->应用状态控制(允许从应用信息页面禁用任何应用)
开启后应用详情里面可以启用APP，但是禁用APP无效。

### 模块日志

LSP的日志复制不了，保存后是个zip，里面文件很多，不知道贴哪个文件的日志。
不过复现步骤我描述的清晰一点，应该很容易就能复现。

### 复现步骤

```bash
1.手机管家->应用状态控制(允许从应用信息页面禁用任何应用)，开启此功能。
2.点击右上角重启手机管家。
3.进入应用详细信息里面，会发现多出了“停用/启用”按钮。
4.点击启用APP没问题，但是点击停用没效果，我测试的是“快应用服务框架”。
（PS：使用其他拥有冻结功能的软件是可以对该“快应用服务框架”进行停用冻结的）
```

### 问题截图

```Markdown
![图片注释](图片链接)
```

### 机型

小米13pro

### MIUI版本

MIUI14 Android 13

### Cemiuiler版本号

1.2.122-20230716

**Comment by Mrqqeat** [comment]
> 

7.7.5-230524.0.3

**Comment by xusheng1987** [comment]
我这也是，应用信息界面无法禁用应用，机型小米13，手机管家版本7.5.4-230317.0.2

**Comment by Mrqqeat** [comment]
> 请问手机管家版本是

7.7.5-230524.0.3
