### ISSUE TITLE
🐛 [BUG] <解锁最小裁切图片限制失效>

### ISSUE THREAD

**Issue by mengyameng** [Team-Cemiuiler/Cemiuiler#217]
### 问题描述

https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/77087199/4dcaae60-4027-41f3-a4d4-f51c83240313

### 模块日志

[LSPosed_2023-07-18T17_03_30.591.zip](https://github.com/Cemiuiler-Development-Team/Cemiuiler/files/12078528/LSPosed_2023-07-18T17_03_30.591.zip)

### 复现步骤

```bash
1、开启“小米相册-编辑---解锁最小裁切图片限制”
2、重启小米相册-编辑
3、裁切图片依然有大小限制
（已选择小米相册-编辑作用域）
```

### 机型

红米

### MIUI版本

MIUI13 Android 12

### Cemiuiler版本号

1.2.122_20230716

**Comment by CJYKK** [comment]
同样的问题，Redmi K40s，MIUI 13.0.7，截图的时候最小尺寸失效了
