### ISSUE TITLE
💡 [需求] 电池优化取消自动恢复默认

### ISSUE THREAD

**Issue by jinyang2004** [Team-Cemiuiler/Cemiuiler#225]
### 需求内容

电池优化取消自动恢复默认

### 实现思路&截图

暂无，大佬们加油

### 简单例子

有些应用比如QQ，勾选了电池优化，一段时间后会自动变为取消勾选。希望可以强制屏蔽自动恢复！

**Comment by 1577223884** [comment]
新版本已经有了。禁止恢复电池优化白名单
