### ISSUE TITLE
💡 [需求] <在设置里添加谷歌服务开关>

### ISSUE THREAD

**Issue by iyhkhtrk** [Team-Cemiuiler/Cemiuiler#232]
### 需求内容

用模块补全后，谷歌服务后台太耗电，在设置里添加跳转或者把开关添加到磁贴，方便低端机开关谷歌服务
图片里的是手机管家的`com.miui.googlebase.ui.GmsCoreSettings`活动

### 实现思路&截图

![Screenshot_2023-07-27-15-58-03-972_com miui securitycenter](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/104120418/83a61288-571c-4976-9577-9bc6e2d81d9a)

### 简单例子

.

**Comment by HChenX** [comment]
已经实现
