### ISSUE TITLE
把最新版本122的双排网速单位改回k，而不是kb

### ISSUE THREAD

**Issue by gjk0510** [Team-Cemiuiler/Cemiuiler#242]
### 需求内容

改回旧版本的单位k就行了，会省下很多空间，或者加个开关也行

### 简单例子

方便观看，不占地方

**Comment by mu7220** [comment]
![Screenshot_2023-08-05-20-27-24-384_com.sevtinge.cemiuiler-edit.jpg](https://github.com/Team-Cemiuiler/Cemiuiler/assets/80700814/b310f3cb-e515-4b0a-ad50-651c7f732506)

请
一直都没变过这个
