### ISSUE TITLE
🐛 [BUG] 夜间模式/深色模式下搜索页面显示异常

### ISSUE THREAD

**Issue by Young-Lord** [Team-Cemiuiler/Cemiuiler#243]
### 问题描述

深色模式下，搜索页面仍为亮色，且无法看清文字

### 模块日志

无

### 复现步骤

```bash
1. 打开夜间模式/深色模式
2. 点击搜索框
3. 输入任意文本
4. 出现问题
```

### 问题截图

![问题截图](https://github.com/Team-Cemiuiler/Cemiuiler/assets/51789698/1211904e-5d30-4f0b-a301-5dc4a85003e5)

### 机型

小米平板5Pro
红米K30 5G

### MIUI版本

MIUI14 Android 13
MIUI13 Android 12

### Cemiuiler版本号

1.2.122_20230716

**Comment by mu7220** [comment]
已在canary版本修复，请等待下一个release版本发布
