### ISSUE TITLE
能不能加一个ban掉杜比音效已启用弹窗的功能

### ISSUE THREAD

**Issue by mark-jiang-1470** [Team-Cemiuiler/Cemiuiler#246]
### 需求内容

就是单纯的希望能隐藏杜比音效已启用的弹窗
![f3cc7f97-7ca3-4da5-ac85-55cd39565183](https://github.com/Team-Cemiuiler/Cemiuiler/assets/78632875/a87bd1d6-4031-444b-8cc1-e942d577ed95)
感觉杜比外放挺好的，就是这个弹窗，一直弹出来，很烦

### 简单例子

就是让这个弹窗不显示，谢谢开发者🙏

**Comment by HChenX** [comment]
复现不出来）

**Comment by mu7220** [comment]
> 复现不出来）
> 

视频类侧滑栏开杜比会弹的（
在考虑做了

**Comment by HChenX** [comment]
> > 复现不出来）
> 
> 视频类侧滑栏开杜比会弹的（ 在考虑做了

试了好多次还是不弹出来，交给你们了（目移

**Comment by HChenX** [comment]
> > > > 复现不出来）
> > > 
> > > 
> > > 视频类侧滑栏开杜比会弹的（ 在考虑做了
> > 
> > 
> > 试了好多次还是不弹出来，交给你们了（目移
> 
> 他这个每天只会弹出一次

这样啊，到时候看看代码吧，大概知道是哪里执行出来的

**Comment by HChenX** [comment]
应该实现了~
