### ISSUE TITLE
核心破解功能冲突

### ISSUE THREAD

**Issue by LittleArray** [Team-Cemiuiler/Cemiuiler#249]
### 问题描述

chemilier中系统框架-包管理服务中的选项会和核心破解模块冲突
具体就是无论是否启用功能，核心破解都无法生效

### 模块日志

]无

### 复现步骤

```bash
1. 前往 '系统框架'
2. 点击 '包管理服务'
3. 启用或关闭任意功能
....
出现问题
```

### 问题截图

![Screenshot](https://github.com/Team-Cemiuiler/Cemiuiler/assets/88972417/b34a123e-3f38-48b2-9c27-7f2fb68618c9)

### 机型

Readmi Note 11T Pro

### MIUI 版本

MIUI14

### Android 版本

Android 13

### Cemiuiler 版本

1.2.122_20230716 | beta

**Comment by yqs112358** [comment]
有了这个是不是不用装核心破解了😲功能重叠

**Comment by LittleArray** [comment]
今早经过一个一个排查，发现是另一个模块的冲突，去提issue了
