### ISSUE TITLE
💡 [需求] 隐藏应用图标

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [Team-Cemiuiler/Cemiuiler#252]
### 需求内容

在miui系统桌面中隐藏指定应用的图标

### 简单例子

以下的例子为个人设想的一些使用场景
例1：如magisk隐藏后，改用快捷方式进入，但启动器图标仍然在(随机包名后的，不是正常图标，如下图)，希望可将其隐藏
例2：部分LSP模块可以直接在LSP中进入设置，希望可以隐藏其桌面图标(有的作者提供了开关，但也有没给的)
例2.1：部分LSP模块并无图形化界面，但安装后仍会在桌面留下图标(类似下图这种)，没用而且占桌面位置，希望可以隐藏
![1691520886208](https://github.com/Team-Cemiuiler/Cemiuiler/assets/87939280/71de6401-4890-4769-9d96-81eddd385156)

说白了就是标题所要求的功能，***隐藏指定应用的图标***
如果可以还希望给个编辑app在桌面所显示的名称的功能(部分名字过长，会变成...强迫症看了很难受 如`Microsoft 365`会变成`Microsoft 3...`)

p.s.之前好像用过有类似功能的工具，但是找不到了，有大佬知道的话可以给个代替品，我先临时用下

**Comment by YaeSakuraQvQ** [comment]
哦...找到了，customiuizer有类似的功能
但他那个隐藏应用不太一样
他那个是基于miui隐藏应用的增强，设想的使用场景应该是隐藏部分应用不被别人发现，并方便再次打开
而我请求的这个功能，是对应app的打开方式已经改变(_如从快捷方式，从LSP中_)或无需打开(_某些无图形化界面的模块_)，所以我这里的需求更近于"**不要在启动器里显示某个不需要的图标**"

**Comment by YaeSakuraQvQ** [comment]
`Cemiuiler-系统桌面-其他` 有 `桌面快捷方式管理`，但只有几个系统应用，要是把这个功能作在这里，让其支持桌面已有的所有app就好了

**Comment by mu7220** [comment]
> `Cemiuiler-系统桌面-其他` 有 `桌面快捷方式管理`，但只有几个系统应用，要是把这个功能作在这里，让其支持桌面已有的所有app就好了

不是几个，更新一下cemiuiler到122版本默认解锁全应用隐藏的

**Comment by YaeSakuraQvQ** [comment]
> > `Cemiuiler-系统桌面-其他` 有 `桌面快捷方式管理`，但只有几个系统应用，要是把这个功能作在这里，让其支持桌面已有的所有app就好了
> 
> 不是几个，更新一下cemiuiler到122版本默认解锁全应用隐藏的

又看了下，我现在的版本就是1.2.122_20230716啊，release里的最新版了，但是确实没看到更多的隐藏功能(只有5个系统应用)，不知道是bug还是我的问题

**Comment by YaeSakuraQvQ** [comment]
`重置模块配置`后问题依旧，尝试完全卸载模块后，从release重新下载最新版安装，问题依旧
应该是bug吧，求修复，大佬试试能否复现吧

**Comment by mu7220** [comment]
> `重置模块配置`后问题依旧，尝试完全卸载模块后，从release重新下载最新版安装，问题依旧
> 应该是bug吧，求修复，大佬试试能否复现吧

请问桌面版本是

**Comment by YaeSakuraQvQ** [comment]
com.miui.home 4.25.1.4565-11291427
miui13 A12
感谢大佬~

**Comment by YaeSakuraQvQ** [comment]
[系统桌面_RELEASE-4.25.1.4565-11291427.apk.zip](https://github.com/Team-Cemiuiler/Cemiuiler/files/12360596/_RELEASE-4.25.1.4565-11291427.apk.zip)
好像只是Cemiuiler的`桌面快捷方式管理`ui里不能显示所有应用，之前用Cemiuiler隐藏过的还是能继续生效的
我提取了一份桌面，大佬需要的话可以看看

**Comment by YaeSakuraQvQ** [comment]
已更新至[1.2.125_20230912](https://github.com/Team-Cemiuiler/Cemiuiler/releases/tag/1.2.125)但仍存在此bug

**Comment by mu7220** [comment]
> 已更新至[1.2.125_20230912](https://github.com/Team-Cemiuiler/Cemiuiler/releases/tag/1.2.125)但仍存在此bug

需要更新系统桌面至 4.39.7 及以上版本

**Comment by YaeSakuraQvQ** [comment]
> > 已更新至[1.2.125_20230912](https://github.com/Team-Cemiuiler/Cemiuiler/releases/tag/1.2.125)但仍存在此bug
> 
> 需要更新系统桌面至 4.39.7 及以上版本

大佬能提取个apk我看看嘛，我现在手机a12的包里最新的版本就只有4.25.1
而且之前用Cemiuiler是可以的(今年6月左右时，当时用的Cemiuiler的具体版本号忘了)，不能写个判断根据版本号同时适配新老版本的桌面嘛

**Comment by YaeSakuraQvQ** [comment]
从apkmirror下到了4.39.7.6217，覆盖安装后就正常了，如果部分功能不适配低版本桌面，建议在该项功能的tip里说明下吧
