### ISSUE TITLE
🐛 [BUG] 包管理服务异常 

### ISSUE THREAD

**Issue by LOVE2CMOL** [Team-Cemiuiler/Cemiuiler#253]
### 问题描述

修改会被检测到 提示 “包管理服务异常 ”

### 模块日志

这个需要日志的话下面补

### 复现步骤

```bash
开启后直接 使用Momo检测
关闭后 检测不到了
```

### 问题截图

![Screenshot_2023-08-09-03-51-52-473_io github vvb2](https://github.com/Team-Cemiuiler/Cemiuiler/assets/28857775/0d92a18b-c25a-450b-bde7-4bea18293d10)
![Screenshot_2023-08-09-03-54-47-594_me weishu kern](https://github.com/Team-Cemiuiler/Cemiuiler/assets/28857775/48bd5556-c185-47d5-bdac-2989090dc32c)
![Screenshot_2023-08-09-03-56-00-713_me weishu kern](https://github.com/Team-Cemiuiler/Cemiuiler/assets/28857775/d2657440-0091-4153-96b3-6fb7ea74fcf4)

已经使用Shamiko白名单模式

### 机型

Xiaomi13

### MIUI 版本

MIUI14

### Android 版本

Android 13

### Cemiuiler 版本

1.2.122_20230716

**Comment by inmk114514** [comment]
建议西米露去除核心破解功能，这样就不会有这个问题了👏

**Comment by inmk114514** [comment]
你自己开了核心破解功能肯定对系统当中的包管理动了手脚的😂

**Comment by Nirvana-EVO** [comment]
被公开处刑了😂
