### ISSUE TITLE
💡 [需求] 屏蔽安全守护开启提示

### ISSUE THREAD

**Issue by 821938089** [Team-Cemiuiler/Cemiuiler#258]
### 需求内容

屏蔽安全守护开启提示

### 简单例子

屏蔽这个
![img](https://github.com/Team-Cemiuiler/Cemiuiler/assets/8674809/04c7182f-8492-4628-af13-e1a87e735f8a)

**Comment by mu7220** [comment]
这个弹窗触发概率低，先摆一段时间再修
