### ISSUE TITLE
🔌 [移植] <控制中心添加显示屏幕刷新率开关(磁贴)>

### ISSUE THREAD

**Issue by xuchaoxin1375** [Team-Cemiuiler/Cemiuiler#269]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

![Screenshot_2023-08-13-16-33-24-266_name monwf customiuizer](https://github.com/Team-Cemiuiler/Cemiuiler/assets/56011806/27e0a111-c50c-411c-a37a-84f514365298)

**Comment by xuchaoxin1375** [comment]
![Uploading Screenshot_2023-08-13-16-42-58-150_com.microsoft.emmx-edit.jpg…]()

**Comment by xuchaoxin1375** [comment]
![Screenshot_2023-08-13-16-42-58-150_com microsoft emmx-edit](https://github.com/Team-Cemiuiler/Cemiuiler/assets/56011806/d4ef1ae7-7ae9-4084-928d-8669b34d7c7c)

**Comment by HChenX** [comment]
还要磁贴啊,吐了。用我写好的TileUtils可以比较轻松的Hook磁贴，比较难的就是设置刷新率了。
我的建议是用scene或者其他的来自动设置刷新率。

**Comment by HChenX** [comment]
@mu7220 把这个关了吧，不会做的
