### ISSUE TITLE
🔌 [移植] <控制app引发振动>

### ISSUE THREAD

**Issue by xuchaoxin1375** [Team-Cemiuiler/Cemiuiler#270]
### 仓库地址

https://github.com/MonwF/customiuizer

### 移植内容

米客的振动控制功能

### 相关描述&截图

![Screenshot_2023-08-13-16-44-39-323_name monwf customiuizer-edit](https://github.com/Team-Cemiuiler/Cemiuiler/assets/56011806/b6588c91-a4dc-433b-af8f-59cc05fea5fe)

![Screenshot_2023-08-13-16-45-12-398_name monwf customiuizer](https://github.com/Team-Cemiuiler/Cemiuiler/assets/56011806/69398f03-4a1e-49e9-ae65-ac6853ae0215)

**Comment by mu7220** [comment]
不打算做
