### ISSUE TITLE
🔌 [移植] <双层状态栏>

### ISSUE THREAD

**Issue by xuchaoxin1375** [Team-Cemiuiler/Cemiuiler#271]
### 仓库地址

https://github.com/yonghen/chimi-

### 移植内容

支持双层状态栏布局

### 相关描述&截图

![Screenshot_2023-08-13-16-49-38-499_com coolapk market](https://github.com/Team-Cemiuiler/Cemiuiler/assets/56011806/1b692a2f-bbd9-421c-b0ca-b99275e8a538)

chimi双层状态栏配置文件导入测试
https://www.123pan.com/s/l7DKVv-CrlsH.html

**Comment by mu7220** [comment]
![Screenshot_2023-08-13-17-38-03-432_tw.nekomimi.nekogram-edit.jpg](https://github.com/Team-Cemiuiler/Cemiuiler/assets/80700814/4e847330-20a5-460d-acf2-1a49a9814870)

投票决定，不打算做
