### ISSUE TITLE
🐛 [BUG] 系统界面中改变通知模糊程度和透明度时，会影响游戏模式的通知

### ISSUE THREAD

**Issue by Ptilopsis01** [Team-Cemiuiler/Cemiuiler#290]
### 问题描述

原本的游戏模式通知是完全透明的，但修改了系统界面选项中与通知相关的设置之后游戏模式下的通知也变成了模糊的，与预期的想法不符

### 模块日志

[LSPosed_2023-08-21T21_55_17.716282.zip](https://github.com/Team-Cemiuiler/Cemiuiler/files/12396749/LSPosed_2023-08-21T21_55_17.716282.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

MI12S

### MIUI 版本

MIUI14

### Android 版本

Android 13

### Cemiuiler 版本

1.2.122_20230716

**Comment by mu7220** [comment]
开启通知设置后就是这个逻辑的，可能之前版本你可能没感知到

**Comment by Ptilopsis01** [comment]
> 开启通知设置后就是这个逻辑的，可能之前版本你可能没感知到

最近才用的，谢谢回复
