### ISSUE TITLE
💡 [需求] <标题> 建议增加移除负一屏最底部推荐栏

### ISSUE THREAD

**Issue by wangyuan0217** [Team-Cemiuiler/Cemiuiler#313]
### 需求内容

![Screenshot_2023-08-29-22-33-06-054_com miui home](https://github.com/Team-Cemiuiler/Cemiuiler/assets/12730214/50bd119e-851e-4d93-b44f-afd542c03115)
如图最底部的推荐栏，增加开关控制影藏。非常感谢！

### 简单例子

1

**Comment by wangyuan0217** [comment]
![image](https://github.com/Team-Cemiuiler/Cemiuiler/assets/12730214/9389b603-6266-41a9-9259-7ec657332d56)
pa_layout_card_recommend_container  这个关键词

**Comment by mu7220** [comment]
![Screenshot_2023-09-06-14-12-58-582_com.miui.personalassistant-edit.jpg](https://github.com/Team-Cemiuiler/Cemiuiler/assets/80700814/9e82a3ac-c9fa-48f0-9691-7ebcb34ebf05)

米米自己智能助理有的，不需要模块

**Comment by wangyuan0217** [comment]
> ![Screenshot_2023-09-06-14-12-58-582_com.miui.personalassistant-edit.jpg](https://user-images.githubusercontent.com/80700814/265910398-9e82a3ac-c9fa-48f0-9691-7ebcb34ebf05.jpg)
> 
> 米米自己智能助理有的，不需要模块

米米自己智能助理有的，   这个是哪里啊；我没找到啊，我是12sp 手机的设置和Cemiuiler里都找过了  没有这个设置啊
