### ISSUE TITLE
💡 [需求] 恢复旧版振动界面

### ISSUE THREAD

**Issue by hamjin** [Team-Cemiuiler/Cemiuiler#325]
### 需求内容

恢复旧版振动界面

### 实现思路&截图

![1693675365651](https://github.com/Team-Cemiuiler/Cemiuiler/assets/30927889/8ae9f50f-ed6b-4a24-a1cb-496d405b7372)

### 简单例子

恢复旧版振动界面，缓解强迫症（大雾）

**Comment by HChenX** [comment]
不会做

**Comment by lswlc33** [comment]
打开国际版设置界面就会自动变成旧版了TAT
