### ISSUE TITLE
🐛 [BUG] 启用Cemiuiler模块后导致MIUI小窗圆角变成直角且无法恢复

### ISSUE THREAD

**Issue by xiaomengxinyo** [Team-Cemiuiler/Cemiuiler#347]
### 问题描述

启用cemiuiler模块后未勾选作用域 系统框架 ，一切正常，勾选系统框架作用域后重启 MIUI小窗的圆角变成了直角，且删除模块后无法恢复

### 模块日志

[LSPosed_2023-09-06T21_11_19.160081.zip](https://github.com/Team-Cemiuiler/Cemiuiler/files/12539559/LSPosed_2023-09-06T21_11_19.160081.zip)

### 复现步骤

```bash
小米13刷入官方最新稳定版系统 MIUI14.0.31.0
通过官网下载并刷入alpha面具最新版
通过Github LSPosed发布页下载最新版并刷入重启
小窗圆角正常
启用Cemiuiler模块并勾选对应作用域后重启(未启用任何修改功能 未授权root)
小窗圆角变直角
关闭模块并清除数据卸载后重启
小窗圆角未恢复
禁用并移除Magisk中的LSPosed模块后重启
小窗圆角恢复正常
重新刷入LSPosed后重启且未启用任何LSPosed模块
小窗圆角变直角
重新在第三方rec刷入完整ROM后刷入面具及LSPosed
小窗依旧是直角
从LSPosed 1.8.4-1.9.1都试过 始终无法让小窗变正常
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-09-06-21-11-05-121_m nfa fztk](https://github.com/Team-Cemiuiler/Cemiuiler/assets/48215946/b40e32ea-7318-4bc7-9015-4614cb19f501)
![0d636bc689746f5f4031b3fe96e70c6e](https://github.com/Team-Cemiuiler/Cemiuiler/assets/48215946/59d88ee0-4dee-4edd-8750-0241ccaaa3e4)
一张为正常圆角 一张为异常圆角

### 机型

Xiaomi 13

### MIUI 版本

MIUI14

### Android 版本

Android 13

### Cemiuiler 版本

1.2.122_20230716

**Comment by mu7220** [comment]
此bug与Magisk版本相关，非Cemiuiler问题，不处理
