### ISSUE TITLE
💡 [需求] <StarVoyager的完整模糊补全效果更好>

### ISSUE THREAD

**Issue by HowLinw** [Team-Cemiuiler/Cemiuiler#358]
### 需求内容

设备小米10S StarVoyager模块的桌面模糊-完整模糊补全可以做到以前12.5/13时候的桌面模糊，不会出现进入后台闪烁模糊延迟

### 实现思路&截图

![Screenshot_2023-09-12-20-46-59-458_star sky voyager](https://github.com/Team-Cemiuiler/Cemiuiler/assets/107696203/b4c25696-7b5d-42b0-93e3-11b42cdaeaf8)

### 简单例子

对比视频
链接：https://caiyun.139.com/m/i?1D5C1oFnJ4bDI 提取码：CNn7

**Comment by mu7220** [comment]
已优化
