### ISSUE TITLE
💡 [需求] <标题>please add all sensor off option

### ISSUE THREAD

**Issue by Manish8580kumar** [Team-Cemiuiler/Cemiuiler#363]
### 需求内容

Sir in new release,s of miui .  Xiaomi has disable the feature available in developer,s option to disable all the sensor available and add a all sensor off tile in the control centor so can u sir please restore that old option that was previously available(still availble but miui remove it)  in android developer option

### 实现思路&截图

Please add all sensor off option in developer option

### 简单例子

Off or shutdown all sensor available in device

**Comment by HChenX** [comment]
Please give me some pictures for reference

**Comment by Manish8580kumar** [comment]
> Please give me some pictures for reference

![images.jpeg](https://github.com/Team-Cemiuiler/Cemiuiler/assets/107913627/d8118f55-8eb1-493f-92e6-13a1f1f05219)

**Comment by HChenX** [comment]
ok ,let me see

**Comment by HChenX** [comment]
Please provide me with your setup installation package. I cannot find the relevant content on my own

**Comment by HChenX** [comment]
in my setting apk,dont have sensors off,please give me your

**Comment by Manish8580kumar** [comment]
https://source.android.com/docs/core/interaction/sensors/sensors-off

**Comment by HChenX** [comment]
![image](https://github.com/Team-Cemiuiler/Cemiuiler/assets/123531821/952712d7-7dfc-4710-8a03-99181b996225)
i will hook it,but i dont sure is it

**Comment by Manish8580kumar** [comment]
> in my setting apk,dont have sensors off,please give me your

Xaiomi has  remove this festure previous year availbale  in developer setting and one of the best privacy feature of android as xaiomi does,nt like  user privacy and want,s all data of users

**Comment by HChenX** [comment]
> > in my setting apk,dont have sensors off,please give me your
> 
> Xaiomi has remove this festure previous year availbale in developer setting and one of the best privacy feature of android as xaiomi does,nt like user privacy and want,s all data of usersXaiomi

if xiaomi setting developer remove this feature , then hook will dont have effect

**Comment by HChenX** [comment]
> > in my setting apk,dont have sensors off,please give me your
> 
> Xaiomi has remove this festure previous year availbale in developer setting and one of the best privacy feature of android as xaiomi does,nt like user privacy and want,s all data of usersXaiomi

you should give me your setting apk , then i can sure

**Comment by Manish8580kumar** [comment]
I don,t know if they remove it or hide it it just not there now and can,t able to find it anywhere in developer setting

**Comment by Manish8580kumar** [comment]
![Screenshot_2023-09-16-21-33-22-403_com.brave.browser.jpg](https://github.com/Team-Cemiuiler/Cemiuiler/assets/107913627/083fec99-33a0-42c6-bda4-1f7046f1972d)

**Comment by HChenX** [comment]
> ![Screenshot_2023-09-16-21-33-22-403_com.brave.browser.jpg](https://user-images.githubusercontent.com/107913627/268458075-083fec99-33a0-42c6-bda4-1f7046f1972d.jpg)

You should give me the xiaomi setting package set up on your phone, not these documents.

**Comment by HChenX** [comment]
> ![Screenshot_2023-09-16-21-33-22-403_com.brave.browser.jpg](https://user-images.githubusercontent.com/107913627/268458075-083fec99-33a0-42c6-bda4-1f7046f1972d.jpg)

You should give me the xiaomi setting package set up on your phone, not these documents.

**Comment by HChenX** [comment]
@mu7220 can close
