### ISSUE TITLE
隐藏正在使用流量加速toast

### ISSUE THREAD

**Issue by lswlc33** [Team-Cemiuiler/Cemiuiler#381]
### 需求内容

![Screenshot_2023-09-24-19-26-34-392_com eg android AlipayGphone](https://github.com/Team-Cemiuiler/Cemiuiler/assets/86835895/ea99f4b0-b13b-4c89-8643-97aa9c09dbcf)

### 简单例子

打开加速名单应用之后不显示toast

**Comment by HChenX** [comment]
有能力就自己写

**Comment by lswlc33** [comment]
> 有能力就自己写

这个字符串在哪个app里我没没找出来😢

**Comment by HChenX** [comment]
这个是在什么情况下会弹出？

**Comment by lswlc33** [comment]
> 这个是在什么情况下会弹出？

打开wifi -网络加速-数据加速后
在连接可用WiFi情况下，任意情况打开网络加速列表中的应用**冷启动**，会弹出toast

**Comment by HChenX** [comment]
> > 这个是在什么情况下会弹出？
> 
> 打开wifi -网络加速-数据加速后 在连接可用WiFi情况下，任意情况打开网络加速列表中的应用**冷启动**，会弹出toast

完成
