### ISSUE TITLE
852c73f8 commit 更新后旧版经典控制中心行列数不生效了

### ISSUE THREAD

**Issue by lukemin** [Team-Cemiuiler/Cemiuiler#400]
Github CI

852c73f8 调整 系统界面-旧版经典控制中心自定义行列数功能；新增 电量与性能-禁止恢复电池优化白名单(#382)

**Comment by mu7220** [comment]
设备 系统版本 安卓版本 都说明一下，我这里 Android13 无问题

**Comment by lukemin** [comment]
小米max3 ，Miui13， Android11 ，没有commit前的版本都是生效的。
