### ISSUE TITLE
🐛 [BUG] 852c73f8 commit 更新后旧版经典控制中心行列数不生效了

### ISSUE THREAD

**Issue by lukemin** [Team-Cemiuiler/Cemiuiler#425]
### 问题描述

852c73f8 commit 更新后旧版经典控制中心行列数不生效了，1.2.128_20231012也不行。

### 模块日志

[LSPosed_2023-10-13T14_47_58.489.zip](https://github.com/Team-Cemiuiler/Cemiuiler/files/12890382/LSPosed_2023-10-13T14_47_58.489.zip)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

小米max3

### MIUI 版本

MIUI13

### Android 版本

Android 12

### Cemiuiler 版本

1.2.128_20231012

**Comment by mu7220** [comment]
已于最新版本做部分回退处理
