### ISSUE TITLE
🐛 [BUG] <Need option Help>

### ISSUE THREAD

**Issue by araafroyall** [Team-Cemiuiler/Cemiuiler#435]
### 问题描述

i attached image and not getting exactly what this featute is

### 模块日志

see screenshot 
![Screenshot_2023-10-17-09-17-08-488_com sevtinge cemiuiler](https://github.com/Team-Cemiuiler/Cemiuiler/assets/87515236/519a9ecd-b4ec-4839-bf49-9ce8c302ca00)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

Redmi Note 10

### MIUI 版本

MIUI12 / MIUI12.5

### Android 版本

Android 11

### Cemiuiler 版本

latest.Today

**Comment by mu7220** [comment]
Fixed, modified its description to "Screen rotation" in Chinese
