### ISSUE TITLE
提供将负一屏中“推荐卡片”删除的功能💡 [需求] <标题>

### ISSUE THREAD

**Issue by fengsha990817** [Team-Cemiuiler/Cemiuiler#444]
### 需求内容

希望能够提供删除负一屏中“推荐卡片”的功能
![1697719572728](https://github.com/Team-Cemiuiler/Cemiuiler/assets/38030455/b92ce19b-be1f-4c8f-961d-c8365ac24c23)

### 简单例子

希望能够提供删除负一屏中“推荐卡片”的功能
![1697719572728](https://github.com/Team-Cemiuiler/Cemiuiler/assets/38030455/b92ce19b-be1f-4c8f-961d-c8365ac24c23)

**Comment by mu7220** [comment]
智能助理设置里面就有（

路径：桌面-桌面设置-智能助理

**Comment by fengsha990817** [comment]
> 官方的智能助理设置里面就有（
> 
> 路径：桌面-桌面设置-智能助理

多谢，路径藏的有些深，之前没翻到
