### ISSUE TITLE
💡 [需求] 增加桌面隐藏App名称功能

### ISSUE THREAD

**Issue by MinecraftXFJ** [Team-Cemiuiler/Cemiuiler#450]
### 需求内容

更新了新版的Cemiuiler，旧版本的系统桌面›图标与标题›文本大小处改成0dp从而使抽屉保留app名称，桌面隐藏app名称的方法失效了，变为了抽屉和桌面均隐藏了app名称，请问可以将使抽屉保留app名称，桌面隐藏app名称的方法独立出来吗

### 实现思路&截图

暂无

### 简单例子

暂无

**Comment by HChenX** [comment]
好！让我突然想起来自己欠的坑

**Comment by HChenX** [comment]
@mu7220 这个可以关了
