### ISSUE TITLE
💡 [需求] 关于通知和控制中心以及状态栏

### ISSUE THREAD

**Issue by IlIllIl** [Team-Cemiuiler/Cemiuiler#90]
### 需求内容

1. 外观：新控制中心亮度条、音量条、WiFi框、流量框矩形圆角调整
2. 外观：通知圆角调整，分别包括悬浮弹出通知、锁屏通知、通知中心通知，不包括展开通知（因为调了有点不好看
3. 改变通知逻辑：置顶单条通知，可以把临时通知固定不能划掉，便于加重点备忘提醒，再点一次按钮取消固定
4. 改变通知逻辑：把开了的通知渠道强制添加声音、振动、常驻（因为有的开了也不会发生声音、振动和常驻，仅仅是权限调整而没有改变本质
5. 外观：通知隐藏右侧展开小圆钮，灰色字更改透明度或变高对比度，即纯黑/白随系统变化（因为开了透明模糊hh...看不清
6. 状态栏的权限和支付环境提醒图标药丸变成圆形，只显示图标不要字（不想直接关
7. 控制中心图标取消分页，不限制最大行数

### 实现思路&截图

![IMG_20230516_203335](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/628219b1-3a34-4b55-a89f-7d64404c9823)
![IMG_20230516_203353](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/13127b1d-f5d4-44e0-b23e-01532f401749)
![IMG_20230516_203743](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/00368e9e-c62f-4c35-98af-c3f659fba27a)
![IMG_20230516_204449](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/d2e4098c-859b-4c4f-b057-00771e8f942d)
![IMG_20230516_205301](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/43d0d479-fad1-41eb-a81d-a5500b8756e1)
![IMG_20230516_205837](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/ad56d7a5-f1c5-45af-830e-e45e34a77040)

### 简单例子

好看好用就够了

**Comment by mu7220** [comment]
3/6/7这边会尝试考虑一下，其他不做
