### ISSUE TITLE
🔌 [需求] 5G面板开关

### ISSUE THREAD

**Issue by IlIllIl** [Team-Cemiuiler/Cemiuiler#91]
### 仓库地址

https://github.com/Xposed-Modules-Repo/com.qingyu.mi5g

### 移植内容

![236685166-9934747c-c98a-43a2-9301-2e82b0c82607](https://github.com/Cemiuiler-Development-Team/Cemiuiler/assets/99599914/6f620230-5d03-41cd-97d9-fa9f3d98cf87)

### 相关描述&截图

已经有磁铁了，但是更喜欢面板开关，原仓库好象不开源，需要自己做...

**Comment by mu7220** [comment]
放到后面再说，目前没有做这个的打算

**Comment by HChenX** [comment]
要写自己写
